### ISSUE TITLE
Automatically hide expression meshes

### ISSUE THREAD

**Issue by ScanMountGoat** [ScanMountGoat/ssbh_editor#1]

**Comment by zrksyd** [comment]
Would it be better to implement that into ssbh_editor or ssbh_wgpu. I was looking into how to do it but I noticed that the main issue is that ssbh_wgpu defaults RenderMesh's is_visible attribute to true and I don't think that's publically accessible.

Here's the equivalent code from CrossMod:
https://github.com/Ploaj/SSBHLib/blob/6bea31fc9f03069120796bb1da006ff87be40cd4/CrossMod/CrossMod/Rendering/Models/RModel.cs#L27

**Comment by ScanMountGoat** [comment]
The visibility for a RenderMesh is public. See the code below for reference. 
https://github.com/ScanMountGoat/ssbh_editor/blob/2159b2ffac35bbec8bfecf3dd482e50ebfa2510c/src/app.rs#L851

This shouldn't be part of ssbh_wgpu since the role of ssbh_wgpu is to render a collection of model folders. This feature would just make a guess based on the mesh names rather than data in the model files. If you want to try implementing this, I would make a menu item for Meshes > Hide Expressions and apply something similar to the Cross Mod code you linked on click. There isn't a perfect way to implement this, so don't worry about doing anything fancy like regex.

I'll get around to adding this eventually, but it isn't a big priority at the moment. Feel free to take a shot at making an implementation.
