### ISSUE TITLE
Default values for added material parameters

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_editor#100]
For example, when CustomVector6 is added to a material, the values should default to 1.0, 1.0, 0.0, 0.0 instead of 0.0, 0.0, 0.0, 0.0

Also the default sampler uses Clamp instead of Repeat by default.

**Comment by ScanMountGoat** [comment]
The default for samplers should be clamp since not all textures are 2D. SSBH Editor already validates texture tiling, so defaulting to clamp to edge is fine. I'll look defaults for the other parameter types.
