### ISSUE TITLE
Animations not assigned to appropriate folder when rendering

### ISSUE THREAD

**Issue by SushiiZ** [ScanMountGoat/ssbh_editor#107]
after updating from 0.6, animations on characters don't seem to play, trying to load animations on sora and he just stays t-posed, animations work fine on 0.6

**Comment by ScanMountGoat** [comment]
Animation playback is still working fine for me. Which animations are you trying to play? There's a bug on 0.6.2 involving zero length animations. If you see "NaN" listed as the current frame, just edit it to be "0.0" instead. This will be fixed for the next release.

**Comment by SushiiZ** [comment]
I’m just trying to load soras fall animation and idle animations

**Comment by ScanMountGoat** [comment]
I'm able to reproduce this with some of Sonic's animations but it seems pretty inconsistent. I'll try and look into this for the next release.

**Comment by ScanMountGoat** [comment]
@SushiiZ This will be fixed on the next release. On the current version (0.6.2), you can fix this by just reloading the current workspace with Ctrl+R or by clicking File > Reload Workspace.
