### ISSUE TITLE
Save camera transformations as defaults

### ISSUE THREAD

**Issue by SushiiZ** [ScanMountGoat/ssbh_editor#108]
When creating animations I like to see it from the same perspective the game would show it, so I usually watch the animations from a left side angle, it'd be cool if we can set camera values and set them as default, same goes for setting fov if that's not implemented yet, and orthodox view, since ult uses a specific value for the fov and is in orthodox view during gameplay, while in perspective for victory animations

**Comment by ScanMountGoat** [comment]
You're probably thinking of "orthographic" cameras that have no perspective foreshortening. Smash Ultimate doesn't actually use an orthographic camera. It just sets the FOV very low, which you can change in the camera settings. I may look into adding a default camera setting at some point. For now, you can always copy paste the same values into the camera settings menu every time you want to render from the same perspective.

**Comment by SushiiZ** [comment]
Ahh yeah you right, and in the game files there are params that refer to the two different camera types

**Comment by ThatNintendoNerd** [comment]
> Smash Ultimate doesn't actually use an orthographic camera. It just sets the FOV very low and places the camera far away

Are you sure about this? Using modified camera controls and a free range of angle of view adjustment, when the angle of view is less than or equal to five degrees, the camera's projection mode will appear to immediately switch from a perspective projection mode to an orthographic projection mode. In programs like Maya, you can select an orthographic camera for the viewport but still adjust distance.

**Comment by ThatNintendoNerd** [comment]
> > > Smash Ultimate doesn't actually use an orthographic camera. It just sets the FOV very low and places the camera far away
> > 
> > 
> > Are you sure about this? Using modified camera controls and a free range of angle of view adjustment, when the angle of view becomes less than or equal to five degrees, the camera's projection mode will appear to immediately switch from a perspective projection mode to an orthographic projection mode. In programs like Maya, you can select an orthographic camera for the viewport but still adjust distance. Granted, I don't know much about the workings of either projection mode beyond surface-level knowledge, so it could be a "fake" or approximation of an orthographic projection mode for all I know.
> 
> The in game cameras use a perspective projection from all the cases I've seen. The formula for a perspective projection has numerical issues like divide by 0 if you set the fov very low or close to 0. It sounds like the game has some way of handling this. It's possible they switch to a different code path with an orthographic camera. I haven't looked into this personally. If you have a way to see what the matrix values are, you can compare the in game values with formulas for the different projection matrices online. Keep in mind most of the matrices will combine other things like the camera's rotation and translation.

If I ever look into the camera on a deeper level than I have, I'll take a look at that. It's possible blujay would know more about this since I believe they've dealt matrices involving the camera for their work on the collision visualizer, but I don't know the specifics of it. Most stages do use a perspective projection mode for their camera, but 75 m, Dream Land GB, Balloon Fight, and Training are the stages that use an orthographic projection mode.

**Comment by ScanMountGoat** [comment]
Being able to change the default camera will be part of the next release (0.9.0).
