### ISSUE TITLE
Misaligned vector drag sliders in MATL Editor

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_editor#110]
![image](https://user-images.githubusercontent.com/6856627/192672209-e15d542f-5969-4864-ba19-953b077823f3.png)
I tried to roughly have the drag sliders be aligned by using ui.monospace instead of ui.label but the monospace font is not working. I wasn't sure if you have a better idea.

**Comment by ScanMountGoat** [comment]
There is no separate monospace font at the moment. SSBH Editor uses a single noto sans font to support multiple languages and having a consistent look for numeric digits. It's probably not worth the added file size to add a monospace version. There should be a way to resolve the layout issues by forcing each label to have a fixed size. You could try experimenting with `ui.add_sized(...);`
