### ISSUE TITLE
Feature Suggestion: Mesh reordering in numdlb, and material reordering in numatb

### ISSUE THREAD

**Issue by SushiiZ** [ScanMountGoat/ssbh_editor#114]
it'd be cool to be able to move meshes and materials around in the numatb and numdlb respectively, you can move meshes around in studiosb and materials you could move around in matlab, it helps for organization to be able to group materials and meshes together

**Comment by ScanMountGoat** [comment]
Numdlb reordering is already implemented. I'm closing this since numatb ordering is discussed in #181.
