### ISSUE TITLE
Bone Re-Ordering Feature Request

### ISSUE THREAD

**Issue by JArmstrongArt** [ScanMountGoat/ssbh_editor#116]
I don't mean to come off entitled or punching above my weight, but I had an idea to make bone re-ordering a bit more convenient.
![image](https://user-images.githubusercontent.com/47801313/195292213-3146cb41-2936-43f5-866b-fff9d75c5837.png)
The arrows on the right-hand side work well enough to swap bones, but moving specific sets of bones a long way across the list takes a long time and is actively quite difficult to focus your eyes on doing.
My idea is to add 2 things, maybe just one of them or maybe both:
1. Put text entry indexes to the left of each bone name. If you change the number in the field, the list readjusts to the new index you typed in for that bone.
![image](https://user-images.githubusercontent.com/47801313/195292042-86387335-e5ce-431a-a692-0cdd36fb8dba.png)
2. Make it so that when you click the arrows on the right whilst holding shift, the bone those arrows belong to moves either all the way to the top of the list or all the way to the bottom of the list respectively.

**Comment by ScanMountGoat** [comment]
This is related to #85. The real issue is that we don't have a good understanding of what the requirements are for ordering bones in custom skeletons. Bone ordering should ideally be handled at export time from applications like Blender. Manually ordering entries isn't a big priority at the moment.

**Comment by JArmstrongArt** [comment]
Oh okay, thanks for the insight. And yeah, as of a few hours ago, Carlos' tool has ben rectified to export swing bones where they ought to be, so it is significantly of less importance. Do consider my design if the priority and reason presents itself to be implemented, but I consider this issue closed now.
