### ISSUE TITLE
Changing Mesh Name in SSBH Not Reflected in-game or in StudioSB (potentially deprecated)

### ISSUE THREAD

**Issue by LargeLeader** [ScanMountGoat/ssbh_editor#120]
Sorry if this is a bugfix you've already implemented, but this issue is from a while ago and I want it up just in case it might point to something fixable:

I changed the name of a mesh in ssbh. The name change is reflected in ssbh editor, but not in studio sb. I also have reason to suspect that the fact it isn't changed in studiosb reflects the fact that the hair mesh still acts as if it is a highmesh instead of a regular, unnamed mesh (ie a mesh that will be visible whether it's docked or undocked)

![HGayL0T](https://user-images.githubusercontent.com/74743796/199325325-9305e79a-9f4d-4e71-8f3b-faca5910f33f.png)

**Comment by ScanMountGoat** [comment]
Did you save the mesh with File > Save in the mesh editor? Is the change reflected in SSBH Editor after you reload the workspace or open the folder again? StudioSB has a lot of bugs, so I wouldn't use it as a reference. You should also see the change using ssbh_lib_json or ssbh_data_json.

**Comment by LargeLeader** [comment]
Solved in updated version of SSBH Editor (the editor shows the name with the _highshape suffix)
