### ISSUE TITLE
Modded NUMATB parsing error

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_editor#121]
I have a kinda complicated NUMATB that I've been working with in CrossMod. It works perfectly fine in game. I was going to work on it in SSBH Editor but it is giving a lot of errors and I cannot figure out why. I tried decoding and reencoding it but it's been giving me the same error.
https://cdn.discordapp.com/attachments/716714927221374996/1038980889994088478/CrossMod.numatb
![image](https://user-images.githubusercontent.com/6856627/200206803-1b584c4d-323a-422c-ac28-b70617550945.png)

**Comment by ScanMountGoat** [comment]
Your numatb has some invalid values. You can fix it following the steps here: https://github.com/ssbucarlos/smash-ultimate-blender/wiki/Known-Blender-Issues#numatb-import-issue
