### ISSUE TITLE
colorSet5.rgb rendering not implemented

### ISSUE THREAD

**Issue by Escope12** [ScanMountGoat/ssbh_editor#122]
Hi. Some of the stages like Delfino Plaza and Spear Pillar aren't rendering their colorsets properly. Also the lighting is not rendering properly. Here are examples.
![path10452](https://user-images.githubusercontent.com/8963276/200741171-e96510f7-b467-4c57-9633-2f3b658cee50.png)
![path10453](https://user-images.githubusercontent.com/8963276/200741173-667a1ee9-fb20-44af-9250-bf505647d281.png)

**Comment by ScanMountGoat** [comment]
The color set rendering bug should be an easy fix for the next release. Stage lighting is only partially researched and won't be implemented anytime soon apart from fighter lighting that's already available in the lighting menu. In this case, the stage is using baked lighting that should hopefully be doable to fix.

**Comment by Escope12** [comment]
Thank you.

**Comment by ScanMountGoat** [comment]
Some stage materials use more complicated blending using the RGBA channels of colorSet5. This applies to the waterfalls on battlefield and the volcano on delfino island. The current renderer only uses the alpha channel, which is causing the textures to not blend properly.

**Comment by Escope12** [comment]
Will that be implemented soon?

**Comment by ScanMountGoat** [comment]
I've worked through most of the shader code for battlefield's waterfall already. I've been busy recently, so I don't have any estimate on when the next SSBH Editor release will be. There's some anim related work on ssbh_data that takes priority since it affects multiple applications and impacts the ability to edit files. I'll let you know when there are any updates on fixing the colorSet5 rendering.

**Comment by Escope12** [comment]
Were the other colorsets rendering implemented as well?

**Comment by ScanMountGoat** [comment]
It looks like everything except for colorSet4, colorSet6, and colorSet7 is implemented to some extent. Some stage materials have different uses of color set attributes that aren't implemented.

**Comment by Escope12** [comment]
I wonder if colorset4, colorset6 and colorset7 will be implemented for rendering in the future? Also is it possible to merge 2 colorsets in Blender?

**Comment by ScanMountGoat** [comment]
I don't plan on working on it anytime soon. They aren't used often, and stages tend to not share as much shader code as fighters. Some assist trophies don't render properly for similar reasons. It would be cool to add at some point, but it would take a lot of work to identify and implement all the variations.
