### ISSUE TITLE
Crash when enabling Draw Bone Axes with Draw Bones enabled

### ISSUE THREAD

**Issue by ThatNintendoNerd** [ScanMountGoat/ssbh_editor#135]
Steps to Reproduce:
1. Open a model with or without a skeleton file (the skeleton file can be populated with joints or empty)
2. Enable Draw Bones from the Render Settings
3. Enable Draw Bone Axes from the Render Settings

System Information:
- Operating System: Windows 10 22H2 19045.2364
- CPU: AMD Ryzen 7 5800H
- GPU: NVIDIA GeForce RTX 3050 Ti
- OpenGL Ver.: 4.6
- Graphics Backend: Any

**Comment by ScanMountGoat** [comment]
Thanks for reporting this. Drawing the bone axes is currently broken due to some renderer rewrites. This will be fixed in the next release.
