### ISSUE TITLE
SSBH Editor "Not Responding" (Windows 11 Nvidia RTX 3000)

### ISSUE THREAD

**Issue by chiefcream** [ScanMountGoat/ssbh_editor#145]
Title says it all. I want to get into cresting smash mods, and I downloaded SSBH Editor and waited for about 10+ minutes and it said "Not Responding" the whole entire time. I am running on Windows 11, so I'm not sure if that's the reason why. I installed the C++ 2015 on the SSBH page and it didn't work. Any fixes?
![F946670D-D833-48F0-961E-B19D1A69A26C](https://user-images.githubusercontent.com/126377461/221396439-e6f1181e-cc21-44ce-ba7a-dafaf0e1ad8e.jpeg)

**Comment by ScanMountGoat** [comment]
This is probably related to the GPU drivers. If you didn't have the C++ runtime installed properly, the application wouldn't start at all. Does your computer meet the [system requirements](https://github.com/ScanMountGoat/ssbh_editor#system-requirements)? 

You can also try changing the graphics backend. The window isn't loading, so you'll need to set it from command prompt following the [steps listed on the wiki](https://github.com/ScanMountGoat/ssbh_editor/wiki/Preferences#graphics-backend). I would try vulkan and DX12. Some GPUs do better with one compared to the other.

**Comment by chiefcream** [comment]
![356B5294-61BD-499E-A90F-3D753922CA99](https://user-images.githubusercontent.com/126377461/221444268-f43f8f81-281e-4cec-98c8-f5b038773e1a.jpeg)

This is what I get, and I installed everything correctly..

**Comment by chiefcream** [comment]
and yes the ssbh_editor.exe is spelled correctly

**Comment by ThatNintendoNerd** [comment]
Because you're using Windows PowerShell, the syntax for executing programs is performed slightly differently. When attempting to run an executable, you need to prefix the name with `./` as if in a Unix operating system, assuming the current working directory contains the executable. This is not the case in Command Prompt, so what you have would work fine there. The full command in Windows PowerShell is like so:
```
./ssbh_editor.exe --backend dx12
```

**Comment by chiefcream** [comment]
I just tried that for both dx12 and vulkan, and both still result in "Not Responding" :/
![image](https://user-images.githubusercontent.com/126377461/221451692-3c2ce2bb-4ceb-4dea-98f3-17e3aee39b7f.jpg)

**Comment by ScanMountGoat** [comment]
What GPU do you have in your computer? If you don't have an Nvidia or AMD graphics card, this would just be the name of your CPU. Even if you have a relatively new computer, there can still be some occasional compatibility issues.

**Comment by chiefcream** [comment]
I have Nvidia GeForce RTX 3050 Ti, and Intel Core i5 11th Generation. This laptop is still new and I've only had it for 2 weeks

**Comment by ScanMountGoat** [comment]
Your computer is definitely new enough. People have had issues with the RTX 3000 series in the past not working properly with Vulkan but working fine with DX12. I've not had any issues personally on my system Windows PC with an RTX 3060 for SSBH Editor 0.8.1. Do you have the latest official GPU drivers from the nvidia website?

**Comment by chiefcream** [comment]
Yes, today I made sure I installed the latest GPU drivers from the Nvidia site. Everything seems to be up to date and it didn't fix the problem

(Also I have noticed once it says "Not responding" and gives me the option to close the program, after it "closes" I can still see it running in Task Manager even after I click end task on SSBH Editor)

**Comment by ScanMountGoat** [comment]
It might not be related to the GPU then. This isn't something I can reliably fix at the moment since I'm not able to reproduce it on my end. I'll leave this issue open in case anything changes or someone else has a similar issue.

**Comment by chiefcream** [comment]
I tried googling to see if anyone else had the same issue, and I only saw one on gamebanana [Link](https://gamebanana.com/questions/34141) 
But I can't read it because it's privited

**Comment by chiefcream** [comment]
But either way thanks for the help, I will try to figure out some fixes to solve this issue when I get home from work

**Comment by chiefcream** [comment]
UPDATE: It works now! I just reinstalled the C++ 2015 and went into NVIDIA Control Panel and selected SSBH to High End Performance and that solved the issue :D

**Comment by ScanMountGoat** [comment]
Glad it's working now. Systems with multiple GPUs can be a bit finicky at times.
