### ISSUE TITLE
Previewing CustomVector8's W component

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_editor#148]
CustomVector8's fourth component controls how transparent a mesh's material is and currently there is no way to preview its effects in SSBH Editor.

**Comment by ScanMountGoat** [comment]
This is an easy fix if someone wants to make a PR on ssbh_wgpu. The outAlpha should be multiplied by the `.a` component of CustomVector8. 

https://github.com/ScanMountGoat/ssbh_wgpu/blob/dd3016b257ea27fe3b932c431441c3ecb67a4559/ssbh_wgpu/src/shader/model.wgsl#L1399-L1402
