### ISSUE TITLE
Rim Lighting in the Viewport on Shaders that Don't Have Rim Lighting (SFX_PBS_0101000800018100)

### ISSUE THREAD

**Issue by BeyondSmash7** [ScanMountGoat/ssbh_editor#160]
v0.8.3 screenshot example:
![image](https://github.com/ScanMountGoat/ssbh_editor/assets/110957189/5409936d-45de-44a1-a834-8ff8ffde74cc)
v0.8.2 screenshot example:
![image](https://github.com/ScanMountGoat/ssbh_editor/assets/110957189/93183adb-9283-4fbc-80cb-3ad43d833a09)
Shader:
![image](https://github.com/ScanMountGoat/ssbh_editor/assets/110957189/41d02fb0-4a01-44d1-859b-3a3443368de6)

**Comment by ScanMountGoat** [comment]
Thank you for including the shader label and screenshots. I'll look into this for the next release since there are a number of other small rendering bugs to fix.

**Comment by BeyondSmash7** [comment]
> Thank you for including the shader label and screenshots. I'll look into this for the next release since there are a number of other small rendering bugs to fix.

No problem. Good work and thank you.
