### ISSUE TITLE
Default Lighting Error Stage Fog

### ISSUE THREAD

**Issue by JoeTEStrikesBack** [ScanMountGoat/ssbh_editor#161]
The default lighting in v0.8.3 seems to be making anything behind the origin point of the viewport (visualized by the red line in the floor grid) appear very slightly darker than anything in front of the viewport's origin point, as seen in this 1st pic:
![image](https://github.com/ScanMountGoat/ssbh_editor/assets/70448342/068f5147-7ddd-4735-b1c7-d29302043c1f)
The error is very subtle, though its existence initially made me think there was a mesh normal seam on one of my other models until I realized it's a lighting error. It does not appear when using any of the debug display modes, & none of the other settings within the render settings tab have any effect on it.

Using the Stage Lighting tab to load in a vanilla copy of the Training Stage's lightset nuanmb fixes the issue:
![image](https://github.com/ScanMountGoat/ssbh_editor/assets/70448342/d69c4599-5d7a-4c24-8fc0-a63f58f705e8)
Changing the lightset also changes the shadow quality, though the shadow quality from the 1st pic was also present in the default lighting from previous releases. Lightsets from other stages work too, but I chose the Training Stage since it's the basis for SSBH's default lighting (which is why everything besides the shadows on the right side of the images are identical.)

The seam & darkening error within the default lighting didn't exist in v0.8.2, as seen in this pic I took a bit over a month ago:
![image](https://github.com/ScanMountGoat/ssbh_editor/assets/70448342/ed25e26c-ea5d-42ce-82a6-c9b65fa7370b)

**Comment by ScanMountGoat** [comment]
I just fixed a fog related bug in the rendering library causing the darkening issue. This should be fixed in the next release.
