### ISSUE TITLE
Modl Editor Animation File Name not editable

### ISSUE THREAD

**Issue by nanobuds** [ScanMountGoat/ssbh_editor#162]
The "animation file name" textbox appears twice, and it does not allow me to type any information in the box.

**Comment by nanobuds** [comment]
![image](https://github.com/ScanMountGoat/ssbh_editor/assets/98193109/367e8207-59a6-4d53-8054-742d988461a0)

**Comment by ScanMountGoat** [comment]
It looks like this was never implemented. The UI is just a placeholder. If I end up needing to implement other features or fixes, this should be easy to add to the next release. Editing numdlb names isn't a big priority, so use ssbh_data_json to edit the numdlb file for now.
