### ISSUE TITLE
UI elements are way too large (SteamOS)

### ISSUE THREAD

**Issue by JerryDELUXE** [ScanMountGoat/ssbh_editor#167]
![image](https://github.com/ScanMountGoat/ssbh_editor/assets/146459906/c2eab1f2-0db7-4ec4-abe1-b29f1d0b49a2)
UI elements are very large. I compiled it on the Steam Deck. Maybe the UI is like that because of the Steam Deck's resolution and Aspect Ratio?

**Comment by ScanMountGoat** [comment]
This looks like some sort of scaling bug. The UI is supposed to scale based on whatever scale factor is reported for the current screen. Is there a UI scale setting you can configure in SteamOS? I would also check if this issue persists on an external monitor if you're able to do that. If this is in fact just a scaling issue, I can try and add a setting to preferences to manually set the scale for the UI.

**Comment by JerryDELUXE** [comment]
> This looks like some sort of scaling bug. The UI is supposed to scale based on whatever scale factor is reported for the current screen. Is there a UI scale setting you can configure in SteamOS? I would also check if this issue persists on an external monitor if you're able to do that. If this is in fact just a scaling issue, I can try and add a setting to preferences to manually set the scale for the UI.

Could only scale up, not down. No idea why.

**Comment by ScanMountGoat** [comment]
Some users reported similar issues on another application and were able to fix it by using gaming mode. https://github.com/ScanMountGoat/ultimate_tex/issues/10

**Comment by ScanMountGoat** [comment]
> Could only scale up, not down. No idea why.

If you have the scaling set to 100% and it still zooms in too much, that's probably an application bug. I'll try and add a manual scaling option for the next release. For now, see if the workaround of using game mode in the other issue I linked works for you.

**Comment by JerryDELUXE** [comment]
Running it in Gaming mode works, not very practical, but works.

**Comment by JerryDELUXE** [comment]
I see you added UI scale. But only the UI scale 2 seems to change everything (Assuming it's finished).

**Comment by ScanMountGoat** [comment]
You should be able to enable a custom scale and choose any floating point number that isn't 0. I can't promise that this will work correctly with steamos though. Let me know if it works correctly for you. A value of 1.0 should disable scaling at least in theory.

**Comment by JerryDELUXE** [comment]
Nevermind it works. Just had to set it to 1 again after opening it for the first time.
