### ISSUE TITLE
Material Editor Numerical Field Crash

### ISSUE THREAD

**Issue by BeverageGaming** [ScanMountGoat/ssbh_editor#175]
Very sorry if this is in any way user error, but I think I've found a bug with the material editor. When working in it and attempting to enter a value in any numerical field by typing it, the moment I click on the field, the program closes. Using the slider feature instead doesn't close it, but as you can imagine, it can be hard to enter precise values with it. I don't know if this is either an issue with the program or perhaps my computer being weird, however I find that I don't have this issue with version 0.8.4.

As a side note, clicking and dragging in any blank area outside the viewport still controls the camera when it didn't in 0.8.4 (this isn't really an issue but I dunno, thought it might be worth mentioning).

**Comment by ScanMountGoat** [comment]
> When working in it and attempting to enter a value in any numerical field by typing it, the moment I click on the field, the program closes.

There was an internal change in the UI library causing the sliders to stop working. This is already fixed on the latest commit. I'll release 0.9.2 with a fix by the end of today.

> As a side note, clicking and dragging in any blank area outside the viewport still controls the camera

This is a separate issue and is being tracked now by #176. This seems pretty minor, so I won't be looking into a fix for the next release (0.9.2).
