### ISSUE TITLE
Color Picker [F] Does not match decimal values to the RGB values

### ISSUE THREAD

**Issue by BeyondSmash** [ScanMountGoat/ssbh_editor#182]
https://github.com/ScanMountGoat/ssbh_editor/assets/110957189/9725748d-2b24-4f1f-9292-7e6f9fd11c8d

![image](https://github.com/ScanMountGoat/ssbh_editor/assets/110957189/7ec09fe1-b17a-4702-91fc-acac639bb8e4)

![image](https://github.com/ScanMountGoat/ssbh_editor/assets/110957189/6c4c5b7f-b00d-4e79-a1c7-91fad1e6ce41)

Once this is solved. I think the copy to clipboard button on the color picker would be much more useful it was supplemented with a paste button so we can just transfer RGB values.

**Comment by ScanMountGoat** [comment]
This looks like some sort of gamma conversion is being applied when converting to floats in the color picker. The floating point values you see in the material editor are the values that will be written to the numatb and rendered in game.

**Comment by BeyondSmash** [comment]
I understand that may be the case, but removing that gamma conversion visual and matching it up with what is in the viewport would make more sense to someone working on editing materials via color picker.

**Comment by ScanMountGoat** [comment]
I've updated the wiki to clarify this. The color picker will be changed to use sRGB gamma for the next release to make the float values match what you see in the editor. The mismatch you see in the color picker won't impact the actual values in game, so I won't be prioritizing a new release any time soon.
