### ISSUE TITLE
Crash with anisotropy and nearest filter mode

### ISSUE THREAD

**Issue by ThatNintendoNerd** [ScanMountGoat/ssbh_editor#190]
Using the latest release of the application, attempting to use a maximum anisotropy of 2x or greater with a texture filtering mode of Nearest causes the application to silently crash.

Steps to Reproduce:
1. Open any model
2. Open Matl Editor
3. Change either the Min Filter or Mag Filter to Nearest
4. Change the Max Anisotropy to 2x or greater

System Information:
- Operating System: Windows 10 22H2 19045.4291
- CPU: AMD Ryzen 7 5800H
- GPU: NVIDIA GeForce RTX 3050 Ti
- OpenGL Ver.: 4.6
- Graphics Backend: Any

**Comment by ScanMountGoat** [comment]
If you want to use anisotropic filtering, both min filter and mag filter should be linear. I'll add this as a validation error instead of a hard crash for the next patch release (0.10.1).
