### ISSUE TITLE
Floor Grid Setting No Longer Works As of Latest Update (0.10.2)

### ISSUE THREAD

**Issue by HappyDile190** [ScanMountGoat/ssbh_editor#193]
When attempting to enable the floor grid on the latest build within the render settings, nothing happens.
![image](https://github.com/ScanMountGoat/ssbh_editor/assets/147209759/6fc68068-3207-429d-b437-8f9a9556b3bd)

**Comment by ScanMountGoat** [comment]
Fixed on latest release: https://github.com/ScanMountGoat/ssbh_editor/releases/tag/0.10.3
