### ISSUE TITLE
Modded NUMATB's causing reading errors

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_editor#196]
I have some old mods (from before SSBH Editor was a thing) and SSBH Editor are unable to read the NUMATB. [MatLab](https://github.com/Ploaj/SSBHLib/releases/) is able to convert the NUMATB to XML and back and they work perfectly fine in-game. If it's possible to modify the MATLab XML to be compatible, I don't really need a change to SSBH Editor.
[yoshi_island_art_yoshi_8ff5c.zip](https://github.com/user-attachments/files/16288256/yoshi_island_art_yoshi_8ff5c.zip) (Yoshi's Island Art Yoshi\fighter\yoshi\model\body\c00)
[lylat_snes.zip](https://github.com/user-attachments/files/16288330/lylat_snes.zip) (Lylat SNES\stage\fox_lylatcruise\normal\model\dyr_zgdiff_set)
![image](https://github.com/user-attachments/assets/87171347-f9f9-41b7-8df5-2c2507373db5)
![image](https://github.com/user-attachments/assets/a5a1002f-adac-4f12-a12f-924556b5d905)

**Comment by ScanMountGoat** [comment]
Change all the 0 values for max anisotropy to 1 and it should work. https://github.com/ssbucarlos/smash-ultimate-blender/wiki/Known-Blender-Issues#numatb-import-issue

**Comment by zrksyd** [comment]
Okay thanks. Is it possible to have SSBH Editor use that as a fallback case if it finds that value while reading?

**Comment by ScanMountGoat** [comment]
The value 0 isn't ever used in game and isn't a meaningful value for anisotropy. It was just a default chosen in legacy code that happened to work in game. I could convert 0 to 1 when reading, but that would not preserve the original data. If you need to convert any legacy files, you can just use an older version of ssbh_lib_json.
