### ISSUE TITLE
Chinese & Japanese characters not recognised

### ISSUE THREAD

**Issue by Cybertron231** [ScanMountGoat/ssbh_editor#2]
As previously mentioned, japanese characters don't show up properly in the application. However, saving anything with these characters causes no issues. 
Screenshot of in application:
![image](https://user-images.githubusercontent.com/89758537/173170681-987ad96d-7a07-4e6c-b633-8d85876911d1.png)
Screenshot of saved nusktb file, with a bone that uses japanese characters:
![image](https://user-images.githubusercontent.com/89758537/173170695-41557299-113f-49e2-a61c-a4298fce11b3.png)

**Comment by ScanMountGoat** [comment]
The current font used by the application doesn't support characters for Chinese or Japanese. This will be fixed for the next release. Thankfully, this is purely a display issue and doesn't actually impact the files themselves.
