### ISSUE TITLE
Move console to main window

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_editor#31]
Remove the console window and instead have it print on a bottom panel similar to StudioSB.
![image](https://user-images.githubusercontent.com/6856627/178165427-b3a16448-cdd7-4e3e-a7c6-0df690a79c76.png)

**Comment by ScanMountGoat** [comment]
What would be some advantages of moving the log messages? Is there information that you expect to see during normal operation of the program?

**Comment by zrksyd** [comment]
I thought you'd wanted to keep it for the end user to see errors or if stuff or whatnot. The current thing with the console makes opening the program on the taskbar a bit annoying and the icon doesn't appear correctly.

**Comment by ScanMountGoat** [comment]
The print statements run before the UI has been initialized, so they won't be able to show up in the main window if something goes wrong. The startup errors will be written to a file for the release builds once I finish #21. The system console window and lack of icon is a temporary thing and should hopefully be changed in the next release or two.

**Comment by zrksyd** [comment]
Are you able to close it once the main window successfully initializes and if it fails, the console stays open?

**Comment by ScanMountGoat** [comment]
The application will be bundled as a desktop application, so it won't open a console at all. Manipulating a system console window would be challenging to get working on all platforms.
