### ISSUE TITLE
Allow "Quick Save" option for each Editor Window.

### ISSUE THREAD

**Issue by DevorySSBU** [ScanMountGoat/ssbh_editor#43]
Essentially, this new option would not open up a window to select the same file you have opened up to replace it. 
The function would just allow changes to overwrite the same file quickly and easily. 
Just like how "Save" and "Save As" are used in other programs.

This would be an additional button to the list where the "Save" button is located. The other button will remain, of course.
The new button can be called "Save", "Quick Save" or "Apply Changes" maybe, to make clear the intention of the function.
If the new button is called "Save", the previous button can be renamed to "Save As"

Mock up for reference:
![save as](https://user-images.githubusercontent.com/96158253/179425279-c8b6d80f-1f8b-4e99-9c64-fa65d2199ff1.png)

**Comment by ScanMountGoat** [comment]
I can add File > Save and File > Save As to all the editors that support saving.
