### ISSUE TITLE
Can't select animations from folders without matching names

### ISSUE THREAD

**Issue by schiggysmallz** [ScanMountGoat/ssbh_editor#49]
animations wont play on 0.5 unless the motion and model folder have the same name
i usually change the cXX to the name of the character when working on mods and i cant preview the animations like this anymore.
and its kinda waste of space that i have to copy the whole motion folder now and give it the same name as the model folder

**Comment by ScanMountGoat** [comment]
The animation and model folder names should match up for in game models. I'm looking into ways of still allowing animations from non matching folders to be available in the drop down list in the Animations tab. This should hopefully be implemented in the next release.

**Comment by schiggysmallz** [comment]
that would be great. thanks for your hard work

**Comment by ScanMountGoat** [comment]
This will be fixed on the next release. All loaded animations from all folders will be available. Matching folders will appear before folders that don't have matching paths in the drop down.
