### ISSUE TITLE
light00.nuanmb implementation in ssbh_editor

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_editor#51]
I know stage lighting is on your to-do list and this is probably the place to start. (I'm not familiar with how much it varies from the animation NUANMB.)

**Comment by ScanMountGoat** [comment]
There's nothing different about the format of light00.nuanmb files compared to model animations. A nuanmb is a nuanmb. ssbh_wgpu already has code for loading lighting data from nuanmb files. I just need to incorporate loading lighting files into ssbh_editor.

**Comment by zrksyd** [comment]
Do you already have something in mind for the program to know whether to load a NUANMB as a model animation or stage lighting file? Does the user have to specify?

**Comment by ScanMountGoat** [comment]
I haven't worked out the details for the UI for loading stage render data. There aren't clear conventions for naming the render folder files, so it would have to be selected manually by the user.
