### ISSUE TITLE
Left panel no longer allows me to view animations

### ISSUE THREAD

**Issue by VaporHFX** [ScanMountGoat/ssbh_editor#56]
This is such a small thing, but I used to be able to click through the left-hand panel to view character animations quickly rather than having to menu through the tab on the right-hand panel (dropdown menu / not being able to quickly scroll makes it a bit more tedius). I had this issue on 0.5.0 and updated to 0.5.1 in hopes that maybe the previous patch had a bug of some sort, but it didn't work on the new update either

If I'm doing something wrong I'd appreciate it if someone could let me know why it's no longer working, but if nothing else having a more convenient way to scroll through animations would be appreciated

**Comment by ScanMountGoat** [comment]
Clicking a nuanmb file in the Files tab will open an editor for animation files in the future. I just forgot to disable making them clickable for now. Animations are no longer applied globally, so it's slightly more work to assign an animation to a specific model.

**Comment by VaporHFX** [comment]
That makes sense and I appreciate the clarification, thank you
