### ISSUE TITLE
Loading LUT textures into renderer

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_editor#59]
Give an option like "Load LUT texture" to apply a "filter" to everything in the renderer. I took a look at ssbh_wgpu and it seems that this code can be repurposed for it perhaps.

https://github.com/ScanMountGoat/ssbh_wgpu/blob/62d38c8fb028216f2b96c7380e0d34d0139502f5/ssbh_wgpu/src/texture.rs#L128

**Comment by ScanMountGoat** [comment]
This will end up being part of loading stage rendering data files like the lighting nuanmb. Most of the code for loading the files is already there. I just need to add some setter methods to `SsbhRenderer`. The stage LUT is one of the last things to be applied before the UI is drawn, so it should work fine as a filter.
