### ISSUE TITLE
Bugs / features involving the animation frame counter

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_editor#60]
BUGS
- As the animation plays, the frame counter will display to the hundredths digit. I'm not sure if this is intentional, but it's inconsistent with dragging the slider, which will only display whole numbers. 
![image](https://user-images.githubusercontent.com/6856627/183318274-dfe304c7-1720-467f-808c-9f0ce112c629.png)
- Dragging the frame counter text box will allow the value to go beyond the range of 0 to the max frame count. 
![image](https://user-images.githubusercontent.com/6856627/183318259-d907b18d-c464-45e9-a732-f5c232e1c00e.png)

FEATURES
- Can arrow keys left and right be used to scrub the animation bar frame by frame while the bar is selected.
- Can you add a loop checkbox (since looping is already the default, I would have the checkbox already checked when the program is booted.)
- Can you add a frame speed? I know the game generally runs at 60 FPS but slowing it down or speeding it up can be useful such as for Fast Special Smash.

I think for the second and third feature requests, some inspiration can be taken from BrawlBox / BrawlCrate.
![image](https://user-images.githubusercontent.com/6856627/183318410-1cb3dfc8-0176-41c3-a6b4-b70bc1953770.png)

**Comment by ScanMountGoat** [comment]
SSBH Editor uses `f32` internally for tracking the current "frame" and interpolates in between frames. This is necessary for handling different framerates and playback speeds. Not seeing whole numbers during playback is normal. The box showing negative values is just a visual bug and has been fixed.

I plan on implementing most of those changes for the animation bar in the future. Another helpful feature will be toggling whether or not SSBH Editor skips frames when rendering. This mostly applies to weaker devices with integrated graphics that may not be able to hit 60 fps consistently.

**Comment by zrksyd** [comment]
Since f32 is used for the current frame anyway, wouldn't it be best to be consistent and show hundredths place while using the slider too?

**Comment by imod-commission** [comment]
It might also be helpful to add a ".<" and ">." button to skip to the frame with expression keyframes

**Comment by ScanMountGoat** [comment]
> Since f32 is used for the current frame anyway, wouldn't it be best to be consistent and show hundredths place while using the slider too?

You would very rarely want to directly select a value like frame `34.5`. You can enter numbers with a decimal by clicking the text box and entering a value. I could show values like `34.00` while dragging, but I'm not sure it makes it any clearer.

> It might also be helpful to add a ".<" and ">." button to skip to the frame with expression keyframes

There isn't a straightforward way of doing this. Suppose the animation is 60 frames long. Tracks will have either 1 frame and last the duration of the animation or 60 baked "keyframes". Most of the track values will be the same from frame to frame. Showing a visual indication for which frames have new values would be helpful, but it wouldn't be the same for every animation or track currently playing. I may look into graphing the values similar to the graph editor Blender.

**Comment by ThatNintendoNerd** [comment]
I've implemented some new buttons to the animation bar. The outer two buttons allow for seeking to the start and end of an animation, respectively, and the inner two buttons advance and rewind an animation by one frame, respectively. Is this something that would be a welcome addition into SSBH Editor, or is a different approach desired?
![image](https://user-images.githubusercontent.com/47584884/201798353-cdf174c8-358e-46b4-83c5-5feff9e01a76.png)

**Comment by zrksyd** [comment]
I think it's alright but it might be best to have that on a new line rather than smushed against the right side
