### ISSUE TITLE
Hlpb Editor 5.2 vs 5.0

### ISSUE THREAD

**Issue by dfox20** [ScanMountGoat/ssbh_editor#67]
So I ran into the leg spazzing out bug and I noticed there was a fix for that by editing the Unk type. On version 5.2 it doesn't let me edit anything that is Unk 1 so I can't actually apply the fix and only allows me to change Unk 2 back to 1.

On version 5.0 though since you can manually type it in instead of the box, it allows me to make the changes I needed to fix the mod. 5.1 has the same issue as 5.2.
![unk 5 0](https://user-images.githubusercontent.com/12885687/184535039-f892502e-6b7f-48f0-8d3b-2e56687b5abc.png)
![unk 5 2](https://user-images.githubusercontent.com/12885687/184535041-085d1725-6a14-4641-9d3d-0afb02271c0e.png)

**Comment by ScanMountGoat** [comment]
This is a typo and will be fixed on the next release. You can use ssbh_data_json or ssbh_lib_json to edit the unk type for now. https://github.com/ultimate-research/ssbh_lib/releases/tag/v0.14.0
