### ISSUE TITLE
Play button moves based on frame counter value

### ISSUE THREAD

**Issue by LargeLeader** [ScanMountGoat/ssbh_editor#8]
The play button will move back and forth as the frame counter values iterates from lower to higher values and then back down to the beginning (e.g. whenever the frame counter goes from a single to double, double to triple, or triple back to single digit values the play button moves around to accommodate the new values).

**Comment by ScanMountGoat** [comment]
This is a fundamental limitation of the more lightweight layout system used to make this application. I've hardcoded the size to reduce the likelihood of this happening.
