### ISSUE TITLE
Feature Suggestion: Bone Coordinates

### ISSUE THREAD

**Issue by SushiiZ** [ScanMountGoat/ssbh_editor#93]
I think it'd be cool to be able to view the bones coordinates during an animation.

Example of usage: I'm currently working on an animation where it has trans movement and I'm looking at a reference animation for the height coordinates to see how high the character goes, but I can't find it when just previewing the animation in ssbh editor. 

I feel like it'd be good to have this as a feature as everyone who mods ultimate would have this program and instead of requiring a 3d model program to see how high a character goes or how far a character goes with their transn movment would make it a lot more streamlined and simple for people

**Comment by ScanMountGoat** [comment]
This is already possible using the Graph tab of the Anim Editor. This won't take into account helper bones, but that shouldn't be an issue for translation.

**Comment by SushiiZ** [comment]
I guess I missed the graph part of it hm, how do I get there
