### ISSUE TITLE
Skeleton Resaving Problem

### ISSUE THREAD

**Issue by ttvJawbreakerX** [ScanMountGoat/ssbh_editor#94]
Pretty big problem regarding saving and editing bones in SSBH. For some reason, when simply saving the bones in the nusktb editor, it completely messes up the model, which can be seen using the CrossMod editor. However, the issue cannot be seen using StudioSB nor SSBH.

I've attached a short video showing off the problem. For reference, all the files im using in Mario's model here are 100% vanilla. https://user-images.githubusercontent.com/112913288/188525569-68399461-62ef-418c-b674-ddd199429af6.mp4

**This is also an issue in-game, everything seen in CrossMod above is exactly how it looks in-game.

So yeah nusktb editor kinda broken, best not to use it for now i guess. :/

**Comment by ScanMountGoat** [comment]
There's nothing to be gained by loading the model in StudioSB or Cross Mod. These applications are not as well developed. You may find one or the other works better in some cases by chance. If this is breaking in game, then I'll try and look into it for the next release. As a temporary measure, use ssbh_data_json for skel edits, which can be downloaded from https://github.com/ultimate-research/ssbh_lib/releases/tag/v0.14.0
