### ISSUE TITLE
Feature Suggestion: 'Hide/Reveal' & 'Collapse/Expand' all Mesh Lists on the right tab.

### ISSUE THREAD

**Issue by DevorySSBU** [ScanMountGoat/ssbh_editor#97]
This would allow for an easier time when managing multiple meshes and experimenting for fighters/stages, more specifically for stages though.
The user would be able to hide every mesh, or even close every list for all meshes in one click, for ease of use in turning 'on certain folders' first, instead of 'closing the majority' first.

A mock-up is created to show a potential visual for this feature. 
![allmeshes](https://user-images.githubusercontent.com/96158253/189467682-862e864f-e72b-4dc4-a107-5e148b773d7b.png)

If this was already planned, I apologize, lol.

**Comment by ScanMountGoat** [comment]
Hiding or showing all meshes in the list should be doable to implement. An "All" entry might be confusing if any of the folders have that name.

**Comment by ScanMountGoat** [comment]
Hiding/showing all meshes will be in the next release. Closing or expanding all folders is more involved. I'll try and look into that for the next release as well.
