### ISSUE TITLE
Feature Suggestion: "Open recent"

### ISSUE THREAD

**Issue by SushiiZ** [ScanMountGoat/ssbh_editor#98]
An open recent menu in the file tab, makes it easy to go back and forth between different folders

**Comment by ScanMountGoat** [comment]
This would be a neat feature. This is waiting for the UI library we're using to support nested menus.

**Comment by SushiiZ** [comment]
Oh sick, thank you

**Comment by SushiiZ** [comment]
Oh sick, looking forward to it
